In [58]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn import datasets
iris= datasets.load_iris()

In [30]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [31]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [33]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [34]:
df['flower']=iris.target

In [35]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     flower  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [36]:
df['flower names']=df['flower'].apply(lambda x: iris.target_names[x])
df['flower names']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: flower names, Length: 150, dtype: object

In [37]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     flower flower names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

# Approach 1: Use train_test_split and manually tune parameters by trial and error

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(iris.data,iris.target,test_size=.2)

In [40]:
model=svm.SVC()

In [41]:
model.fit(X_train,y_train)

SVC()

# Accuracy of the model

model.score(X_test,y_test)

# Check how the model predicting and put it in dataframe

In [47]:
df1=pd.DataFrame(model.predict(X_test))
df1

0
0   2
1   1
2   0
3   0
4   0
5   2
6   1
7   0
8   2
9   2
10  1
11  0
12  0
13  2
14  1
15  1
16  2
17  2
18  2
19  2
20  2
21  1
22  0
23  0
24  1
25  0
26  1
27  0
28  2
29  2

# Check the test data and put it in dataframe

In [48]:
df2=pd.DataFrame(y_test)
df2

0
0   2
1   1
2   0
3   0
4   0
5   1
6   1
7   0
8   2
9   2
10  1
11  0
12  0
13  2
14  1
15  1
16  2
17  2
18  2
19  2
20  2
21  1
22  0
23  0
24  1
25  0
26  1
27  0
28  1
29  2

# Merging the dataframes to check the accuracy of the model predicting y and y_test data

In [52]:
df_merge=pd.concat([df1,df2], axis='columns')
df_merge

0  0
0   2  2
1   1  1
2   0  0
3   0  0
4   0  0
5   2  1
6   1  1
7   0  0
8   2  2
9   2  2
10  1  1
11  0  0
12  0  0
13  2  2
14  1  1
15  1  1
16  2  2
17  2  2
18  2  2
19  2  2
20  2  2
21  1  1
22  0  0
23  0  0
24  1  1
25  0  0
26  1  1
27  0  0
28  2  1
29  2  2

# Approach 2: Use K Fold Cross validation

Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [55]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [56]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

Above approach is tiresome and very manual. We can use for loop as an alternative

In [59]:
kernels = ['rbf', 'linear'] # list defined
C = [1,10,20] # list defined
avg_scores = {} # empty dictionary created to put the values
for k in kernels:
    for c in C:
        cv_scores = cross_val_score(svm.SVC(kernel=k,C=c,gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[k + '_' + str(c)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

From above results we can say that rbf with C=1 or 10 or linear with C=1 will give best performance

# Approach 3: Use GridSearchCV

GridSearch does same as loop in concrete way

In [65]:
from sklearn.model_selection import GridSearchCV

# Below block of code has to be executed together

In [66]:
model= GridSearchCV(svm.SVC(gamma='auto'),{
                                            'C':[1,10,20],
                                           'kernel':['rbf','linear']
                                          }, cv=5,return_train_score=False)
model.fit(iris.data,iris.target)
model.cv_results_

{'mean_fit_time': array([0.00139947, 0.00060568, 0.00058036, 0.0005096 , 0.00052528,
        0.00042915]),
 'std_fit_time': array([1.08963867e-03, 4.49133018e-05, 1.22049822e-05, 3.94308868e-05,
        4.65226437e-05, 1.50834379e-05]),
 'mean_score_time': array([0.0007247 , 0.00039015, 0.00034137, 0.00030627, 0.00031357,
        0.00026679]),
 'std_score_time': array([4.66505162e-04, 1.68544230e-05, 1.38220280e-05, 1.86708389e-05,
        2.33043155e-05, 6.97226590e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [68]:
df_gridsearch=pd.DataFrame(model.cv_results_)
df_gridsearch

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001399      0.001090         0.000725        0.000467       1   
1       0.000606      0.000045         0.000390        0.000017       1   
2       0.000580      0.000012         0.000341        0.000014      10   
3       0.000510      0.000039         0.000306        0.000019      10   
4       0.000525      0.000047         0.000314        0.000023      20   
5       0.000429      0.000015         0.000267        0.000007      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [74]:
df_gridsearch[['param_C','param_kernel','mean_test_score']] # 2-D array needs to be passed as argument

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

# Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. This is useful when you have too many parameters to try and your training time is longer. It helps reduce the cost of computation

In [75]:
from sklearn.model_selection import RandomizedSearchCV

In [79]:
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),
                              {'kernel':['rbf','linear'],'C': [1,10,20]},cv=5, return_train_score=False,n_iter=2)
rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001252      0.000447         0.000711        0.000157          rbf   
1       0.000723      0.000117         0.000454        0.000129       linear   

  param_C                         params  split0_test_score  \
0      20     {'kernel': 'rbf', 'C': 20}           0.966667   
1      20  {'kernel': 'linear', 'C': 20}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0                0.9           0.966667                1.0   
1                1.0                0.9           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.036515                1  
1         0.966667        0.042164                2

In [80]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      20       linear         0.966667