In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [30]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# Data cleaning- Removing Nan from 2 columns

In [31]:
median=df['test_score(out of 10)'].median()
median

8.0

In [34]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
def safe_word_to_num(word):
    if isinstance(word,str):
        try: # to handle incorrect 
            return w2n.word_to_num(word)
        except ValueError:
            return 0 # Handle incorrect word formats gracefully
    else:
            return 0 # return 0 for non-string
        
df['experience']=df['experience'].apply(safe_word_to_num)
df
    

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
def safe_word_to_num(word):
    if isinstance(word,str):
        try: # to handle incorrect 
            return w2n.word_to_num(word)
        except ValueError:
            return 0 # Handle incorrect word formats gracefully
    else:
            return 0 # return 0 for non-string
        
df['experience']=df['experience'].apply(safe_word_to_num)
df

# Multivariate Regression

# Y = m1x1 + m2x2+ m3x3+ b

# Split the data into features (X) and target (y)

In [39]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression()

In [40]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [41]:
reg.intercept_

17737.263464337688

In [42]:
reg.predict([[8,9,7]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([72288.93740902])

In [43]:
reg.predict([[2,9,6]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [44]:
reg.predict([[12,10,10]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])